# Generated by Django 4.1 on 2022-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_note_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
